name: build astro pnpm

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:

jobs:
  build-assets:
    name: Build assets
    runs-on: ubuntu-latest

    steps:
      - name: Use repo
        uses: actions/checkout@v4

      - name: Use PNPM & install
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - name: Build Astro
        run: |
          pnpm i --engine-strict
          pnpm run build