name: build with gulp

on:
  workflow_dispatch:

jobs:
  one:
    name: the first
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Build
        run: npm i
