name: build pnpm

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:

jobs:
  build-assets:
    name: Build assets
    runs-on: ubuntu-latest

    steps:
      - name: Use repo
        uses: actions/checkout@v2

      - name: Use PNPM & install
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: true

      - name: Gulp build
        run: pnpm gulp --env=prod
