name: deployment rsync

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Use repo
        uses: actions/checkout@v2

      - name: Remove dev files
        run: |
          shopt -s extglob
          shopt -s dotglob
          rm -r !("app"|"public_html")

      - name: Deploy files
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          REMOTE_HOST: ${{ secrets.PROD_SSH_HOST }}
          REMOTE_USER: ${{ secrets.PROD_SSH_USER }}
          TARGET: '/home/demo.com/'
