name: deployment rsync (2)

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Use repo
        uses: actions/checkout@v2

      - name: Remove dev files
        run: |
          echo --- BEFORE
          ls -a
          shopt -s extglob
          shopt -s dotglob
          rm -r !("app"|"public_html")
          echo
          echo --- AFTER
          ls -a

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          remote_path: /home/demo.com/
          remote_host: ${{ secrets.PROD_SSH_HOST }}
          remote_user: ${{ secrets.PROD_SSH_USER }}
          remote_key: ${{ secrets.PROD_SSH_KEY }}
