name: deployment rsync

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Use repo
        uses: actions/checkout@v2

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: ''
          REMOTE_HOST: ${{ secrets.PROD_SSH_HOST }}
          REMOTE_USER: ${{ secrets.PROD_SSH_USER }}
          TARGET: '/home/demo.com/'
          # sends all files, or 1 dir
