name: gulp pnpm

on:
  workflow_dispatch:

jobs:
  build:
    name: Build CSS & JS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: true

      - name: Run Gulp build
        run: pnpm gulp --env=prod
