name: gulp yarn

on:
  workflow_dispatch:

jobs:
  build:
    name: Build CSS & JS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Build with yarn
        run: yarn install
        run: npx gulp --env=prod
