name: gulp npm

on:
  workflow_dispatch:

jobs:
  build:
    name: Build CSS & JS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install packages
        run: npm i
      - name: Run Gulp build
        run: npx gulp --env=prod
