name: gulp yarn

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:

jobs:
  build-assets:
    name: Build assets
    runs-on: ubuntu-latest

    steps:
      - name: Use repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Yarn install
        run: yarn install

      - name: Gulp build
        run: npx gulp --env=prod
